### ISSUE TITLE
引用的文字没有换行

### ISSUE THREAD

**Issue by hongyuanw** [hejianxian/hexo-theme-jane#12]
你好，用的你的这个主题，很简洁，有个小问题就是>这个引用markdown解析后该有的换行都丢失了，比如http://yuanwhy.com/2016/09/29/mysql-innodb_flush_log_at_trx_commit/ ； 简书的解析就有原始换行http://www.jianshu.com/p/e3a67cf4d7ba

**Comment by hejianxian** [comment]
谢谢！

其实这个问题是因为我将blockquote里的p元素的margin设为0，页面看起来就没了撑开的间隔。

``` css
.article-entry blockquote p {
    margin: 0;
    margin-bottom: 1.6em;
    text-align: justify;
    word-wrap: break-word;
}
```

把bottom撑开，就有换行的效果。

相关样式已经修改，请更新主题代码。
